name: Test

on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  web-ext:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            .venv
            .cache
            .wdm
            .npm
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/poetry.lock') }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to current branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install browser firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "latest"
        if: ${{ matrix.browser == 'firefox' }}

      - name: Install browser chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: "stable"
        if: ${{ matrix.browser == 'chrome' }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          npm ci --cache .npm --prefer-offline
          npm install --global npm
          npm install --global rollup web-ext
          poetry config virtualenvs.in-project true
          poetry install
          npm install

      - name: Create .zip package
        run: npm run build

      - name: Execute web-ext lint
        run: web-ext lint --ignore-files=src/js/**

  selenium:
    strategy:
      matrix:
        # Use only lower and higher versions
        instance: [11.0, 16.0]
        browser: [chrome, firefox]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            .venv
            .cache
            .wdm
            .npm
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/poetry.lock') }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to current branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install browser firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "latest"
        if: ${{ matrix.browser == 'firefox' }}

      - name: Install browser chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: "stable"
        if: ${{ matrix.browser == 'chrome' }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          npm ci --cache .npm --prefer-offline
          npm install --global npm
          npm install --global rollup
          poetry config virtualenvs.in-project true
          poetry install
          npm install

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Create .zip package
        run: npm run build

      - name: Run test for ${{ matrix.instance }} (${{ matrix.browser }})
        id: xtests
        run: xvfb-run --auto-servernum npm run tests -- --capture=no --browser ${{ matrix.browser }} --odoo-version ${{ matrix.instance }}
